### ISSUE TITLE
CMD+Enter?

### ISSUE THREAD

**Issue by sc0ttkclark** [NikV/bbPress-command-enter#5]
Would be nice :)

**Comment by NikV** [comment]
Sure, will get it implemented real soon.

**Comment by pippinsplugins** [comment]
After using this for a bit, I realized I would actually prefer CMD + Enter.

Perhaps you could setup an option in the Forums setting to choose the
keyboard short cut that is used?

**Comment by NikV** [comment]
@sc0ttkclark @pippinsplugins CMD+Enter added! I'll start the options stuff soon as well.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by NikV** [comment]
Re-did a lot of the plugin with feedback from a few people. I took out Shift + Enter since it seemed other shortcuts would be better.

**Comment by pippinsplugins** [comment]
Are you planing to push this .org at any point?

**Comment by NikV** [comment]
@pippinsplugins Yep! Just wrapping up a bit with the code to make sure everything works properly.

**Comment by pippinsplugins** [comment]
:+1:
